version: '3.8'

volumes:
  patientdb:
  
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patients
    ports:
      - "8081:3306"
    volumes:
      - patientdb:/data/db


  patient-api:
    build: .
    container_name: patient
    depends_on:
          - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patients
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DATABASE: patients
    ports:
      - "8081:8080"
      