-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 20:37:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema patients
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `patients` ;

-- -----------------------------------------------------
-- Schema patients
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `patients` DEFAULT CHARACTER SET utf8 ;
USE `patients` ;

-- -----------------------------------------------------
-- Table `patients`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patients`.`patients` ;

CREATE TABLE IF NOT EXISTS `patients`.`patients` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `family_Name` VARCHAR(45) NULL,
  `first_Name` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `gender` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`patient_id`),
  UNIQUE INDEX `idpatients_UNIQUE` (`patient_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
